# Generated by Django 5.1.2 on 2024-11-21 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0002_alter_word_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯЁё]*$', 'Для ввода разрешены только буквы.')]),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯЁё]*$', 'Для ввода разрешены только буквы.')]),
        ),
    ]
